### ISSUE TITLE
ERROR:client:Caught exception in on_connect: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Gollum-Ralf** [tillsteinbach/WeConnect-mqtt#151]
Hello Tim,

I have not been getting any data from Weconnect for a few days now. I then updated the container ( The image is from 2022-08-24 12:06:42), but the problem persists. Strangely enough, only with my Passat. But not with the ID 3 of my wife.

The full log from Portainer looks like this:

2022-09-19T12:35:00+0200:ERROR:client:Caught exception in on_connect: invalid literal for int() with base 10: '',
Exception in thread Thread-1 (_thread_main):,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner,
    self.run(),
  File "/usr/local/lib/python3.10/threading.py", line 953, in run,
    self._target(*self._args, **self._kwargs),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main,
    self.loop_forever(retry_first_connection=True),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever,
    rc = self._loop(timeout),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop,
    rc = self.loop_read(),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read,
    rc = self._packet_read(),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read,
    rc = self._packet_handle(),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle,
    return self._handle_connack(),
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack,
    on_connect(,
  File "/usr/local/lib/python3.10/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 583, in on_connect_callback,
    self.updateWeConnect(),
  File "/usr/local/lib/python3.10/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 444, in updateWeConnect,
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective),
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 181, in update,
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective),
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 199, in updateVehicles,
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict, fixAPI=self.fixAPI,,
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 124, in __init__,
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective),
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 218, in update,
    self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective),
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 330, in updateStatus,
    self.domains[domain.value][key] = className(vehicle=self, parent=self.domains[domain.value], statusId=key,,
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/warning_lights_status.py", line 30, in __init__,
    super().__init__(vehicle=vehicle, parent=parent, statusId=statusId, fromDict=fromDict, fixAPI=fixAPI),
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/generic_status.py", line 38, in __init__,
    self.update(fromDict=fromDict),
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/warning_lights_status.py", line 53, in update,
    self.warningLights[warningLightDict['messageId']] = WarningLightsStatus.WarningLight(fromDict=warningLightDict,,
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/warning_lights_status.py", line 100, in __init__,
    self.update(fromDict),
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/warning_lights_status.py", line 113, in update,
    self.priority.fromDict(fromDict, 'priority'),
  File "/usr/local/lib/python3.10/site-packages/weconnect/addressable.py", line 301, in fromDict,
    self.setValueWithCarTime(int(fromDict[key]), lastUpdateFromCar=None, fromServer=True),
ValueError: invalid literal for int() with base 10: '',

If you could have a look there please?

Thank you very much!

Ralf

**Comment by tillsteinbach** [comment]
Sure, I will have a look what is going wrong.

**Comment by tillsteinbach** [comment]
@Gollum-Ralf can you try the new release 0.40.0?

**Comment by Gollum-Ralf** [comment]
Hello Tim,

thank you very much for the incredibly fast help!

It is now working again as before. You have eliminated the error!

Thank you very much!

Ralf

**Comment by tillsteinbach** [comment]
Great! Will close this one!
