### ISSUE TITLE
Exception with honkAndFlashControl

### ISSUE THREAD

**Issue by msome** [tillsteinbach/WeConnect-mqtt#154]
Good morning, 
version 0.40.0 of the Docker image creates an exception and does not publish data to mqtt.

Would be nice if you could take a look.

2022-09-23T05:10:37+0000:**ERROR:client:Caught exception in on_connect: 'NoneType' object has no attribute 'enabled'**
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 585, in on_connect_callback
    self.updateWeConnect()
  File "/usr/local/lib/python3.10/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 446, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 181, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 199, in updateVehicles
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict, fixAPI=self.fixAPI,
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 124, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 218, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/vehicle.py", line 372, in updateStatus
    self.controls.update()
  File "/usr/local/lib/python3.10/site-packages/weconnect/elements/controls.py", line 67, in update
    self.honkAndFlashControl.enabled = False  # TODO: Remove this line when the endpoint becomes available

**Comment by msome** [comment]
0.40.1 works again. Thanks for quick fixing.

**Comment by tillsteinbach** [comment]
Thanks for reporting!
