### ISSUE TITLE
No data is obtained from VW

### ISSUE THREAD

**Issue by Gollum-Ralf** [tillsteinbach/WeConnect-mqtt#182]
Hello Mr Steinbach,

My wife drives an ID 3 (taken over May 22) and I drive a Passat GTE (taken over Dec. 20). Unfortunately, I now have the problem that the data update, after the Docker container start, no longer works after only a few days. In my home automation system IP-Symcon, however, a ping request from your service continues to arrive. 

![grafik](https://user-images.githubusercontent.com/47719096/211554561-0a4023f9-9cc8-47a2-bc03-d79fe08d322e.png)

When I stop and restart the Docker container, the data is updated immediately. And the data can also be read out via the WeConnect app.

Is it also possible to view a log in the Docker version of your service? I couldn't find anything in Portainer at the last minute.

Best regards

Ralf Gronau

**Comment by tillsteinbach** [comment]
I recently discovered that too. I think this might happen when the connection to the broker is lost. I will investigate further.

**Comment by tillsteinbach** [comment]
Regarding the logging you have to increas loglevel by adding e.g. `-vv` to the `ADDITIONAL_PARAMETERS`. This will increse the loglevel

**Comment by Gollum-Ralf** [comment]
Hello Mr Steinbach,

Yesterday the data retrieval stopped again. But this time I was able to recognise something with a corresponding log entry.  Alternatively, you could perhaps include a parameter that restarts the system at a time to be specified as a parameter!


2023-02-14T19:49:14+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T19:49:14+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T19:54:15+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T19:54:22+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T19:54:22+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T19:54:22+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T19:59:22+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T19:59:22+0100:INFO:openid_session:Token expired,
2023-02-14T19:59:22+0100:INFO:we_connect_session:Refreshing tokens,
2023-02-14T20:00:25+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:00:25+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:00:25+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:05:26+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:05:28+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:05:28+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:05:28+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:10:29+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:10:31+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:10:31+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:10:31+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:15:32+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:15:34+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:15:34+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:15:34+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:20:34+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:20:37+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:20:37+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:20:37+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:25:38+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:25:50+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:25:50+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:25:50+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:30:50+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:30:53+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:30:53+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/2: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:30:53+0100:WARNING:departure_timers_status:/vehicles/WVWZZZ3CZME051453/domains/departureTimers/departureTimersStatus/timers/3: Unknown attribute targetSOC_pct with value 100,
2023-02-14T20:35:54+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:35:55+0100:CRITICAL:weconnect_mqtt_base:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions,
2023-02-14T20:35:55+0100:INFO:weconnect_mqtt_base:Client successfully disconnected,
2023-02-14T20:36:06+0100:INFO:weconnect_mqtt_base:WeConnect-mqtt 0.41.1 (using WeConnect-python 0.50.1),
2023-02-14T20:36:06+0100:INFO:weconnect_mqtt_base:Connect to WeConnect,
2023-02-14T20:36:06+0100:INFO:weconnect_mqtt_base:Connected to MQTT broker,
2023-02-14T20:36:06+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:36:07+0100:ERROR:client:Caught exception in on_connect: You have to login at myvolkswagen.de and accept the terms and conditions,
Exception in thread Thread-1 (_thread_main):,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner,
    self.run(),
  File "/usr/local/lib/python3.11/threading.py", line 975, in run,
    self._target(*self._args, **self._kwargs),
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main,
    self.loop_forever(retry_first_connection=True),
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever,
    rc = self._loop(timeout),
         ^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop,
    rc = self.loop_read(),
         ^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read,
    rc = self._packet_read(),
         ^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read,
    rc = self._packet_handle(),
         ^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle,
    return self._handle_connack(),
           ^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack,
    on_connect(,
  File "/usr/local/lib/python3.11/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 585, in on_connect_callback,
    self.updateWeConnect(),
  File "/usr/local/lib/python3.11/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 446, in updateWeConnect,
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective),
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 191, in update,
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective),
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 199, in updateVehicles,
    data = self.fetchData(url, force),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 364, in fetchData,
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False),
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get,
    return self.request("GET", url, **kwargs),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 69, in request,
    return super(WeConnectSession, self).request(,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/openid_session.py", line 192, in request,
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/openid_session.py", line 229, in addToken,
    self.login(),
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 76, in login,
    response = self.doWebAuth(authorizationUrl),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth,
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions'),
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions,
2023-02-14T20:41:06+0100:INFO:weconnect_mqtt_base:Update data from WeConnect,
2023-02-14T20:41:08+0100:CRITICAL:weconnect_mqtt_base:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions,


Best regards
Ralf Gronau

**Comment by tillsteinbach** [comment]
The problem here is that you actively have to login at Volkswagen and accept the new terms and conditions. This is something the software cannot recover from itself.
