### ISSUE TITLE
no update from vw-api

### ISSUE THREAD

**Issue by do6uk** [tillsteinbach/WeConnect-mqtt#196]
Since afternoon of 14.02.2023 the client can connect, but not receive any data on update. It seems VW changed something at the API. 

There was a "confirm therms"-message and since this moment the API does not respond as expected. I accepted the terms, checked weconnect-mqtt is up to date, but it can't receive data from API. 

Connection is established, but client logged:

weconnect_mqtt_base:API compatibility error during update.

WeConnect APP is still working

**Comment by tillsteinbach** [comment]
That is strange. I had the same message, but after accepting the new terms everything works again. Can you send me some logs after restarting the container?

**Comment by diplix** [comment]
same for me as @tillsteinbach describes, worked for me again after accepting the new terms. prior to accepting the new terms for a couple of hours i got this error:

> API compatibility error during update.

**Comment by do6uk** [comment]
Log with -vv
[log_vv.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/10740960/log_vv.txt)

Log with -vvv
[log_vvv.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/10740959/log_vvv.txt)

Okay ... what I tried so far ...
weconnect-mqtt doesn't work > accept-terms message in log
login myvolkswagen > accept terms
restart weconnect-mqtt > message as described in my post
stopped weconnect-mqtt > tryed update via pip
restarted weconnect-mqtt > message still there
[log_vvv.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/10740959/log_vvv.txt)
[log_vv.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/10740960/log_vv.txt)

login myvolkswagen > no more terms-message, car-data is up to date
restarted weconnect-mqtt > message still there
re-installed weconnect-mqtt > message still there

--version reports 0.41.2 and WeConnect-python 0.51.1
running on debian bullseye

is there any temp-data produced by weconnect-mqtt which I could try to clean?
any idea what I could try else?

**Comment by softservicegit** [comment]
Hi, I have problems too. After accepting the Terms and conditions the container starts fine. But no data is coming.

There is an error published by mqtt:
code -7
"API compatibility error during update. Will try again after configured interval of 300s"

Update to the latest release doesnt change anything.

**Comment by softservicegit** [comment]
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/7657884/218987160-17f8973f-406f-47bc-916d-74b99c37cd55.png">

**Comment by tillsteinbach** [comment]
Hmmm, I cannot reproduce the error here. I can just imagine that the server behaves differently for different users. Maybe they are still updating things?

**Comment by softservicegit** [comment]
Valid guess :)

<img width="287" alt="image" src="https://user-images.githubusercontent.com/7657884/219005333-4cc7bec3-007e-4061-887c-6a7b8cd5721e.png">

**Comment by do6uk** [comment]
wonder why original app is still working .,. thougt this is using same api
perhaps the car is relevant ... in my case egolf

**Comment by tillsteinbach** [comment]
I can see a slight difference in the communication. In your case the server answers with a 303 redirect where it answers with a 302 for me. But it is unclear to me what exactly triggers the error. If it will not solve itself or appear on my account I have to find someone giving me access to an account that fails.

**Comment by tillsteinbach** [comment]
If someone has time he could execute this script: https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/allVehicles.py this might give an error that allows us to better trace it down.

**Comment by softservicegit** [comment]
At 13:36:21 it resumes to a normal state. No error anymore. 
Looks like VW was still playing around with the API.

**Comment by tillsteinbach** [comment]
Good to hear that!

**Comment by do6uk** [comment]
here still not working

**Comment by do6uk** [comment]
> If someone has time he could execute this script: https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/allVehicles.py this might give an error that allows us to better trace it down.

#  Initialize WeConnect
#  Login
Traceback (most recent call last):
  File "/home/rainer/scripts/wec-test.py", line 30, in <module>
    main()
  File "/home/rainer/scripts/wec-test.py", line 19, in main
    weConnect.login()
  File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided

**Comment by tillsteinbach** [comment]
Hmmm, let’s wait a bit more if it fixes itself also for you.

**Comment by PieBa** [comment]
I also had issues since 2023-02-15 (see error log below)

The message in the error-log clearly stated that I had to "_login at myvolkswagen.de and accept the terms and conditions_"
Today I did so and restarted the WeConnect-mqtt service. I immediately received the data as before.
So for me it seems everything is working fine again without any code changes, just by accepting terms and conditions at myvolkswagen.de.

```
2023-02-15T17:41:10+0100:ERROR:client:Caught exception in on_connect: You have to login at myvolkswagen.de and accept the terms and conditions
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 472, in on_connect_callback
    self.updateWeConnect()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 363, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 175, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 182, in updateVehicles
    data = self.fetchData(url, force)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 344, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 165, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 200, in addToken
    self.login()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 49, in login
    response = self.doWebAuth(authorizationUrl)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 199, in doWebAuth
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions
2023-02-15T17:43:06+0100:CRITICAL:weconnect_mqtt_base:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions
```

**Comment by PieBa** [comment]
> If someone has time he could execute this script: https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/allVehicles.py this might give an error that allows us to better trace it down.

This is my output
(I replaced some personal details by [I removed that]

```
#  Initialize WeConnect
#  Login
#  update
/vehicles/WVW[I removed that]: Unknown attribute brandCode with value V
/vehicles/WVW[I removed that]/domains/access/accessStatus: Unknown attribute doorLockStatus with value locked
/vehicles/WVW[I removed that]/domains/charging/chargingStatus: Unknown attribute chargeType with value
/vehicles/WVW[I removed that]/domains/charging/chargingStatus: Unknown attribute chargingSettings with value
/vehicles/WVW[I removed that]/domains/charging/plugStatus: Unknown attribute externalPower with value unavailable
/vehicles/WVW[I removed that]/domains/charging/plugStatus: Unknown attribute ledColor with value none
/vehicles/WVW[I removed that]: Unknown domain departureTimers with value {'departureTimersStatus': {'value': {'carCapturedTimestamp': '2023-02-07T18:47:57Z', 'heaterSource': 'electric', 'minSOC_pct': 20, 'timers': [{'id': 1, 'enabled': True, 'charging': True, 'climatisation': False, 'targetSOC_pct': 100, 'preferredChargingTimes': [{'id': 1, 'enabled': True, 'startTimeLocal': '19:31', 'endTimeLocal': '03:29'}], 'recurringTimer': {'departureTimeLocal': '03:30', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']}}, {'id': 2, 'enabled': False, 'charging': False, 'climatisation': False, 'targetSOC_pct': 0, 'recurringTimer': {'departureTimeLocal': '11:00', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']}}, {'id': 3, 'enabled': False, 'charging': False, 'climatisation': False, 'targetSOC_pct': 0, 'recurringTimer': {'departureTimeLocal': '11:00', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']}}]}}}
#  print results
VIN:               WVW[I removed that]
Model:             e-Golf
Device Platform:   MBB
Nickname:          [I removed that]
Role:              PRIMARY_USER
Enrollment Status: COMPLETED
User Role Status:  ENABLED
Co-Users: 1 items
        Id: [I removed that],  Role: SECONDARY_USER,  Reseted: False,  Enrollment Status: NOT_STARTED
Capabilities: 33 items
        [access] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [automation] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [charging] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [climatisation] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2030-08-06T13:08:00+00:00)
        [departureProfiles] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [departureTimers] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [destinations] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
        [emergencyCalling] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [fuelStatus] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [honkAndFlash] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [measurements] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [news] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
        [oilLevelStatus] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [parkingInformation] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
        [parkingPosition] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [roadsideAssistant] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [state] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [transactionHistoryAntiTheftAlert] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [transactionHistoryAntiTheftAlertDelete] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [transactionHistoryHonkFlash] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [transactionHistoryLockUnlock] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [tripStatistics] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [vehicleHealth] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [vehicleHealthArchive] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [vehicleHealthInspection] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [vehicleHealthSettings] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [vehicleHealthTrigger] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [vehicleHealthWakeUp] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [vehicleHealthWarnings] disabling: False (expires 2030-08-06T13:08:00+00:00)
        [vehicleLights] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [vehicleWakeUp] disabling: False (expires 2023-08-06T13:08:00+00:00)
        [vehicleWakeUpTrigger] disabling: False (expires 2023-08-06T13:08:00+00:00)
Domains: 12 items
[access] Elements: 1 items
        [accessStatus] (last captured 2023-02-17T18:19:39+00:00)
                Overall Status: safe
                Doors: 6 items
                        bonnet: closed
                        frontLeft: closed
                        frontRight: closed
                        rearLeft: closed
                        rearRight: closed
                        trunk: closed
                Windows: 6 items
                        frontLeft: closed
                        frontRight: closed
                        rearLeft: closed
                        rearRight: closed
                        roofCover: unsupported
                        sunRoof: unsupported
[automation] Elements: 2 items
        [climatisationTimer]
                Error:  Error 4104: Bad Gateway
                        info: Looks like your service has expired. Please update your service subscription.
                        timestamp: 2023-02-18 13:50:44+00:00
                Timers: 0 items
        [chargingProfiles]
                Error:  Error 4104: Bad Gateway
                        info: Looks like your service has expired. Please update your service subscription.
                        timestamp: 2023-02-18 13:50:44+00:00
                        Profiles: 0 items
[userCapabilities] Elements: 1 items
        [capabilitiesStatus]
                Capabilities: 33 items
                        [access] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [automation] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [charging] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [climatisation] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2030-08-06T13:08:00+00:00)
                        [departureProfiles] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [departureTimers] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [destinations] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
                        [emergencyCalling] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [fuelStatus] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [honkAndFlash] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [measurements] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [news] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
                        [oilLevelStatus] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [parkingInformation] Status: MISSING_LICENSE disabling: False (expires 2021-08-06T13:08:00+00:00)
                        [parkingPosition] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [roadsideAssistant] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [state] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [transactionHistoryAntiTheftAlert] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [transactionHistoryAntiTheftAlertDelete] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [transactionHistoryHonkFlash] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [transactionHistoryLockUnlock] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [tripStatistics] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [vehicleHealth] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [vehicleHealthArchive] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [vehicleHealthInspection] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [vehicleHealthSettings] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [vehicleHealthTrigger] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [vehicleHealthWakeUp] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [vehicleHealthWarnings] disabling: False (expires 2030-08-06T13:08:00+00:00)
                        [vehicleLights] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [vehicleWakeUp] disabling: False (expires 2023-08-06T13:08:00+00:00)
                        [vehicleWakeUpTrigger] disabling: False (expires 2023-08-06T13:08:00+00:00)
[charging] Elements: 5 items
        [batteryStatus] (last captured 2023-02-17T18:18:52+00:00)
                Current SoC: 41%
                Range: 91km
        [chargingStatus] (last captured 2023-02-17T18:18:52+00:00)
                State: notReadyForCharging
                Remaining Charging Time: 0 minutes
        [chargingSettings] (last captured 2023-02-17T18:18:40+00:00)
                Maximum Charge Current AC: maximum
        [chargeMode]
                Error:  Error 4105: Bad Gateway
                        info: Upstream service responded with an unexpected status. If the problem persists, please contact our support.
                        timestamp: 2023-02-18 13:50:44+00:00
        [plugStatus] (last captured 2023-02-17T18:18:52+00:00)
                Plug: disconnected, unlocked
[climatisation] Elements: 3 items
        [climatisationStatus] (last captured 2023-02-17T18:19:04+00:00)
                State: off
        [climatisationSettings] (last captured 2023-02-17T18:18:40+00:00)
                Target Temperature in °C: 18.0 °C
                Target Temperature in °F: 64.0 °F
                Climatization without external Power: True
        [windowHeatingStatus] (last captured 2023-02-08T07:21:37+00:00)
                Windows: 2 items
                        front: off
                        rear: off
[fuelStatus] Elements: 1 items
        [rangeStatus] (last captured 2023-02-17T18:19:39+00:00)
                Car Type: electric
                Total Range: 91 km
                Primary Engine: electric  SoC: 41% (91 km)
[vehicleLights] Elements: 1 items
        [lightsStatus] (last captured 2023-02-17T18:19:39+00:00)
                Lights: 2 items
                        right: off
                        left: off
[vehicleHealthInspection] Elements: 1 items
        [maintenanceStatus] (last captured 2023-02-17T18:19:28+00:00)
                Current milage: [I removed that] km
                Inspection due in: 155 days
                Inspection due in: 24300 km
[vehicleHealthWarnings] Elements: 1 items
        [warningLights] (last captured 2023-02-07T13:56:13+00:00)
                Current milage: [I removed that] km
                Warning Lights: []
[oilLevel] Elements: 1 items
        [oilLevelStatus]
                Error:  Error 4004: Bad Gateway
                        info: Something went wrong. Please try to re-login. If the problem persists, please contact our support.
                        timestamp: 2023-02-18 13:50:44+00:00
[measurements] Elements: 2 items
        [rangeStatus] (last captured 2023-02-17T18:19:39+00:00)
                Electric Range: 91km
        [odometerStatus] (last captured 2023-02-17T18:19:39+00:00)
                Odometer: [I removed that] km
[parking] Elements: 1 items
        [parkingPosition] (last captured 2023-02-17T18:19:08+00:00)
                Latitude: [I removed that]
                Longitude: [I removed that]

#  done
```

**Comment by PieBa** [comment]
> > If someone has time he could execute this script: https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/allVehicles.py this might give an error that allows us to better trace it down.
> 
> ```
> #  Initialize WeConnect
> #  Login
> Traceback (most recent call last):
>   File "/home/rainer/scripts/wec-test.py", line 30, in <module>
>     main()
>   File "/home/rainer/scripts/wec-test.py", line 19, in main
>     weConnect.login()
>   File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 182, in login
>     self.__session.login()
>   File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
>     response = self.doWebAuth(authorizationUrl)
>   File "/home/rainer/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
>     raise APICompatibilityError('No user id provided')
> weconnect.errors.APICompatibilityError: No user id provided
> ```

It seems to me, you didn't provide --username and --passwort?

**Comment by tillsteinbach** [comment]
And there is definitely no dialog for terms and conditions coming when you login at: https://www.myvolkswagen.net ?

**Comment by tillsteinbach** [comment]
good to hear that it was solved for you!
