### ISSUE TITLE
No data. KeyError: 'location' issue when trying to connect

### ISSUE THREAD

**Issue by marcelrv** [tillsteinbach/WeConnect-mqtt#199]
Running my first time weconnect-mqtt trying to get the data.
Unfortunately it stops with KeyError: 'location'  or that may be related to a 404 error 

in the mqtt there is not yet a raw json topic to inspect, prob it terminates prior to the creation of that.

```
~/WeConnect-mqtt$ weconnect-mqtt --username test@test.de --password test123 --mqttbroker 192.168.0.1  --prefix weconnect --with-raw-json-topic  -vvv
2023-02-27T17:21:54+0100:INFO:weconnect_mqtt_base:WeConnect-mqtt 0.42.1 (using WeConnect-python 0.54.0)
2023-02-27T17:21:54+0100:INFO:weconnect_mqtt_base:Connect to WeConnect
2023-02-27T17:21:54+0100:DEBUG:addressable:: Observer added with flags: ObserverEvent.VALUE_CHANGED|DISABLED|ENABLED
2023-02-27T17:21:54+0100:DEBUG:client:Sending CONNECT (u0, p0, wr1, wq1, wf1, c1, k60) client_id=b''
2023-02-27T17:21:54+0100:DEBUG:client:Received CONNACK (0, 0)
2023-02-27T17:21:54+0100:INFO:weconnect_mqtt_base:Connected to MQTT broker
2023-02-27T17:21:54+0100:DEBUG:client:Sending SUBSCRIBE (d0, m4) [(b'weconnect/mqtt/weconnectForceUpdate_writetopic', 2)]
2023-02-27T17:21:54+0100:DEBUG:client:Sending PUBLISH (d0, q1, r1, m5), 'b'weconnect/mqtt/weconnectUpdateInterval_s'', ... (3 bytes)
2023-02-27T17:21:54+0100:DEBUG:client:Sending SUBSCRIBE (d0, m6) [(b'weconnect/mqtt/weconnectUpdateInterval_s_writetopic', 1)]
2023-02-27T17:21:54+0100:INFO:weconnect_mqtt_base:Update data from WeConnect
2023-02-27T17:21:54+0100:DEBUG:connectionpool:Starting new HTTPS connection (1): login.apps.emea.vwapps.io:443
2023-02-27T17:21:54+0100:DEBUG:connectionpool:https://login.apps.emea.vwapps.io:443 "GET /authorize?redirect_uri=weconnect%3A%2F%2Fauthenticated&nonce=174866072212873039011677515034 HTTP/1.1" 404 77
2023-02-27T17:21:54+0100:ERROR:client:Caught exception in on_connect: 'location'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/home/marcel/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 610, in on_connect_callback
    self.updateWeConnect()
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 462, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/weconnect.py", line 202, in updateVehicles
    data = self.fetchData(url, force)
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/weconnect.py", line 367, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
  File "/home/marcel/.local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/auth/openid_session.py", line 192, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/auth/openid_session.py", line 235, in addToken
    self.login()
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/home/marcel/.local/lib/python3.8/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/home/marcel/.local/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```
(note: I tried with my regular credentials/mqtt server, not the dummy ones)

**Comment by gapthorpe** [comment]
(Duplicates https://github.com/tillsteinbach/VWsFriend/issues/435 )

**Comment by funcarver72** [comment]
Hello Mr. Steinbach,
same issue on my side.  Docker container running stable for weeks, but crashed today and cannot be started again - same messages in error log as described above.

**Comment by marcelrv** [comment]
> Note that if I go with regular browser to the url https://login.apps.emea.vwapps.io/authorize?redirect_uri=weconnect%3A%2F%2Fauthenticated&nonce=174866072212873039011677515034
> 
> I get a page with: `404 Not Found: Requested route ('login.apps.emea.vwapps.io') does not exist.`

Looking at the android app, I see the following URLS related to login
https://identity.vwgroup.io
https://id.vwgroup.io
https://emea.bff.cariad.digital/user/v2/

but I'm sure you digged already much deeper into the app

**Comment by tillsteinbach** [comment]
Please update to the latest release 0.42.2

**Comment by Rocksteady0815** [comment]
Thanks for quick fixing the issue. It is working again!

**Comment by marcelrv** [comment]
Thanks for fixing so quickly!

**Comment by funcarver72** [comment]
Thanks also from my side for this quick fix. I can confirm, that the latested docker container works again.
