### ISSUE TITLE
feature: accepting terms at myvolkswagen required > send notification to mqtt-topic

### ISSUE THREAD

**Issue by do6uk** [tillsteinbach/WeConnect-mqtt#207]
Today my instance stopped working again, due to "accept terms" message at login. Perhabs it is possible to publish this information to an mqtt-topic, so that I can monitor this in my Node-RED automation and send a notification to my mobile device.

**Comment by diplix** [comment]
that’s what i thought today, too. may be even more generic, pipe certain weconnect errors to a mqtt topic?

**Comment by tillsteinbach** [comment]
Did you check what mqtt/error/code and mqtt/error/message give? I‘m not 100% sure right now.

**Comment by do6uk** [comment]
Yes ... I found some traceback in my syslog ...

`Mar  8 07:09:01 localhost systemd[1]: weconnect.service: Succeeded.
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]: 2023-03-08T07:09:02+0100:ERROR:client:Caught exception in on_connect: You have to login at myvolkswagen.de and accept the terms and conditions
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]: Exception in thread Thread-1:
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]: Traceback (most recent call last):
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.run()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self._target(*self._args, **self._kwargs)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3591, in _thread_main
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.loop_forever(retry_first_connection=True)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     rc = self._loop(timeout)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1164, in _loop
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     rc = self.loop_read()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     rc = self._packet_read()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     rc = self._packet_handle()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     return self._handle_connack()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     on_connect(
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 610, in on_connect_callback
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.updateWeConnect()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 462, in updateWeConnect
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/weconnect.py", line 193, in update
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/weconnect.py", line 202, in updateVehicles
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     data = self.fetchData(url, force)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/weconnect.py", line 367, in fetchData
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 600, in get
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     return self.request("GET", url, **kwargs)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/auth/we_connect_session.py", line 69, in request
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     return super(WeConnectSession, self).request(
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/auth/openid_session.py", line 192, in request
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/auth/openid_session.py", line 235, in addToken
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     self.login()
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/auth/we_connect_session.py", line 76, in login
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     response = self.doWebAuth(authorizationUrl)
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:   File "/usr/local/lib/python3.9/dist-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]:     raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
Mar  8 07:09:02 localhost weconnect-mqtt[1824412]: weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions`
