### ISSUE TITLE
Error code -6

### ISSUE THREAD

**Issue by jbval** [tillsteinbach/WeConnect-mqtt#30]
Hello,
since this afternoon, i've got a connexion error in the mqtt stream.

'''Retrieval error during update. Will try again after configured interval of 300s'''
code error -6

The last data I received was at 2021-09-27T14:33:44+00:00
Am I the only one?
Thanks

**Comment by tillsteinbach** [comment]
No you are not alone. The servers respond with a "500 Internal Server Error" nothing we can do here.

But what should happen is that it continues to try every 300 seconds. Did it die completely? if yes, can you send me the logs?

**Comment by jbval** [comment]
Thanks for your feedback, at least I know the problem is not on my docker installation. 
I Just have the logs inside mqtt. I'm using the docker version.
What log do you need and where can i find it ?
I have another docker with the iddatalogger project but it may use another server or way to get data as it still works (but the mqtt integration is the most efficient way to sync with my domotic's box)

**Comment by tillsteinbach** [comment]
You can get the logs like that: https://docs.docker.com/engine/reference/commandline/logs/

Is the container still running, or  did it exit?

**Comment by jbval** [comment]
The container is still running.

Here are the last logs I can fetch (I just changed the VIN number) :

`Exception in thread Thread-118:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 440, in __refreshToken
    raise RetrievalError(f'Status Code from WeConnect server was: {refreshResponse.status_code}')
weconnect.errors.RetrievalError: Status Code from WeConnect server was: 400
Exception in thread Thread-123:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 395, in __refreshToken
    if refreshResponse.status_code == requests.codes['unauthorized']:
UnboundLocalError: local variable 'refreshResponse' referenced before assignment
Exception in thread Thread-136:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 395, in __refreshToken
    if refreshResponse.status_code == requests.codes['unauthorized']:
UnboundLocalError: local variable 'refreshResponse' referenced before assignment
ERROR:weconnect:Failed to retrieve data for VIN XXX: Could not retrieve vehicle status data. Status Code was: 504
`

**Comment by tillsteinbach** [comment]
Thanks! Can you try to update to the latest version? I think the error you are seeing was already fixed in 0.14.12

**Comment by jbval** [comment]
I'll try asap and tell you the result (just need to read the documentation about upgrading a container :p )

**Comment by jbval** [comment]
Everything seems fine with the last docker image !
Thanks for your help

**Comment by tillsteinbach** [comment]
Great!
