### ISSUE TITLE
Frequent "RuntimeError: OrderedDict mutated during iteration" errors

### ISSUE THREAD

**Issue by guyeeba** [tillsteinbach/WeConnect-mqtt#331]
Hi all,

I encounter the above error in every few days, and it causes weconnect-mqtt to stop running, and systemd does not restart it even with Restart=on-failure

I use v0.49.0 on Ubuntu 22.04.3 LTS with parameters

--username my@email.address --password mypassword --mqttbroker 127.0.0.1 --mqtt-username weconnectuser --mqtt-password weconnectpassword --prefix weconnect -i 300 --update-on-connect

Call stack:
<pre>
Mar 23 00:22:38 app1 python[446752]: Exception in thread paho-mqtt-client-:
Mar 23 00:22:38 app1 python[446752]: Traceback (most recent call last):
Mar 23 00:22:38 app1 python[446752]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Mar 23 00:22:38 app1 python[446752]:     self.run()
Mar 23 00:22:38 app1 python[446752]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Mar 23 00:22:38 app1 python[446752]:     self._target(*self._args, **self._kwargs)
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4517, i>
Mar 23 00:22:38 app1 python[446752]:     self.loop_forever(retry_first_connection=True)
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2291, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self._loop(timeout)
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1680, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self.loop_read()
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2094, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self._packet_read()
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3137, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self._packet_handle()
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3799, i>
Mar 23 00:22:38 app1 python[446752]:     return self._handle_pubackcomp("PUBACK")
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4457, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self._do_on_publish(mid, reasonCode, properties)
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4427, i>
Mar 23 00:22:38 app1 python[446752]:     rc = self._update_inflight()
Mar 23 00:22:38 app1 python[446752]:   File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4226, i>
Mar 23 00:22:38 app1 python[446752]:     for m in self._out_messages.values():
Mar 23 00:22:38 app1 python[446752]: RuntimeError: OrderedDict mutated during iteration
</pre>

Any ideas how to resolve it?

Thanks in advance

**Comment by skvist60** [comment]
Hi,

I have this same issue, it started showing up about a week ago. It appears to happen at random times for me. 

I tried updating paho-mqtt to the latest version, which is newer than the version required by reconnect-mqtt, but with the same result.
