### ISSUE TITLE
Weconnect-MQTT stopped working

### ISSUE THREAD

**Issue by tomm1ed** [tillsteinbach/WeConnect-mqtt#370]
Getiting the following error:

```
weconnect-mqtt_1  | Traceback (most recent call last):
weconnect-mqtt_1  |   File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
weconnect-mqtt_1  |     sys.exit(main())
weconnect-mqtt_1  |              ^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 343, in main
weconnect-mqtt_1  |     mqttCLient.run()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 782, in run
weconnect-mqtt_1  |     self.updateWeConnect()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 462, in updateWeConnect
weconnect-mqtt_1  |     self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 194, in update
weconnect-mqtt_1  |     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 205, in updateVehicles
weconnect-mqtt_1  |     data = self.fetchData(url, force)
weconnect-mqtt_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 373, in fetchData
weconnect-mqtt_1  |     statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
weconnect-mqtt_1  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
weconnect-mqtt_1  |     return self.request("GET", url, **kwargs)
weconnect-mqtt_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
weconnect-mqtt_1  |     return super(WeConnectSession, self).request(
weconnect-mqtt_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 194, in request
weconnect-mqtt_1  |     url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
weconnect-mqtt_1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 238, in addToken
weconnect-mqtt_1  |     self.login()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
weconnect-mqtt_1  |     response = self.doWebAuth(authorizationUrl)
weconnect-mqtt_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
weconnect-mqtt_1  |     afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
weconnect-mqtt_1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
weconnect-mqtt_1  |     return self.request("GET", url, **kwargs)
weconnect-mqtt_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
weconnect-mqtt_1  |     return super(WeConnectSession, self).request(
weconnect-mqtt_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt_1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 188, in request
weconnect-mqtt_1  |     raise InsecureTransportError()
weconnect-mqtt_1  | oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by arnoldu** [comment]
I have the same error message since a couple of days. I found the hint somewhere do disable this error by injecting:
```
import os                                                                                                     
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```
into /usr/local/bin/weconnect-mqtt, but to no avail - now I receive "Error -6 ... unknown socket error", this worked with my ID.4 for a long time quite satisfying.

**Comment by nefiertsrebliS** [comment]
you have to agree to the privacy policy on the VW-homepage and then restart weconnect. After that everything will be fine again.

**Comment by tomm1ed** [comment]
> you have to agree to the privacy policy on the VW-homepage and then restart weconnect. After that everything will be fine again.

This was indeed the solution. Thank you!
