### ISSUE TITLE
VW ID3 got an Update

### ISSUE THREAD

**Issue by TheWolfaw** [tillsteinbach/WeConnect-mqtt#372]
Got this error since then:

Exception in thread Update in Background:
Traceback (most recent call last):
  File "C:\Users\OpenAdmin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\OpenAdmin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect_mqtt\weconnect_mqtt_base.py", line 462, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\weconnect.py", line 194, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\weconnect.py", line 205, in updateVehicles
    data = self.fetchData(url, force)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\weconnect.py", line 373, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\openid_session.py", line 194, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\openid_session.py", line 238, in addToken
    self.login()
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "C:\OpenHAB\WeConnect\python\lib\site-packages\weconnect\auth\openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

**Comment by Benka184** [comment]
I have exactly the same thing. Unfortunately it no longer works. Last Update 28-11-2024

**Comment by tillsteinbach** [comment]
You need to logout and in again in the Volkswagen app to accept the new terms and conditions.

**Comment by Domoberry** [comment]
fwiw: in my case weconnect-mqtt (v0.49.0 and weconnect-python 0.60.3) also did not update anymore since  2024-11-28 22:20:14. The status of the program reported 'failed' (RPI4). Using the suggestion, I logged into the WeConnect website. This included accepting Terms & Conditions. Thereafter. Weconnect-mqtt started working again (after a while). Also upgraded to 0.49.2 and 0.60.5.

**Comment by TheWolfaw** [comment]
Ahh ok thanks alot. didn't think of login to the webpage to get the new Terms & Conditions. Now it Works!
