### ISSUE TITLE
OAuth2 InsecureTransportError

### ISSUE THREAD

**Issue by Nugman** [tillsteinbach/WeConnect-mqtt#377]
I start weconnect-mqtt via systemd with these parameters:
```shell
/usr/local/bin/weconnect-mqtt --mqttbroker mqtt.lan --netrc /usr/local/etc/weconnect.conf --pictures --picture-format png --convert-times Europe/Berlin --republish-on-update --interval=300
``` 

Every 5 minutes the service is restarted with an error:
```
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]: Traceback (most recent call last):
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     sys.exit(main())
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 343, in main
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     mqttCLient.run()
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 782, in run
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     self.updateWeConnect()
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 462, in updateWeConnect
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/weconnect.py", line 194, in update
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/weconnect.py", line 205, in updateVehicles
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     data = self.fetchData(url, force)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/weconnect.py", line 373, in fetchData
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     return self.request("GET", url, **kwargs)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/we_connect_session.py", line 69, in request
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     return super(WeConnectSession, self).request(
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/openid_session.py", line 194, in request
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/openid_session.py", line 238, in addToken
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     self.login()
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/we_connect_session.py", line 76, in login
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     response = self.doWebAuth(authorizationUrl)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     return self.request("GET", url, **kwargs)
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/we_connect_session.py", line 69, in request
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     return super(WeConnectSession, self).request(
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:   File "/usr/local/lib/python3.10/dist-packages/weconnect/auth/openid_session.py", line 188, in request
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]:     raise InsecureTransportError()
Dec 14 14:07:52 mqtt weconnect-mqtt[45693]: oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
Dec 14 14:07:52 mqtt systemd[1]: weconnect.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 14:07:52 mqtt systemd[1]: weconnect.service: Failed with result 'exit-code'.
Dec 14 14:07:52 mqtt systemd[1]: weconnect.service: Scheduled restart job, restart counter is at 2149.
Dec 14 14:07:52 mqtt systemd[1]: Stopped WeConnect.
Dec 14 14:07:52 mqtt systemd[1]: Started WeConnect.
``` 

weconnect conf looks like:

```
# For WeConnect
machine volkswagen.de
login xyz@abcd.de
password xxxxxxxxxxxxxxxxxxx
account yyyy

# For the MQTTBroker
machine mqtt.lan
login weconnect
password xxxxxxxxxxxxxxxxxxxxxxxxx
``` 

This configuration used to work for 8 weeks or so and suddenly stopped working 10 days ago. Is this a bug? Any hints?

**Comment by tillsteinbach** [comment]
No, you need to accept new terms and conditions. Easiest is to logout the app and in again. It will ask you to consent.

**Comment by Nugman** [comment]
That helped. Many thanks!

**Comment by koleo9am** [comment]
Hi, in my case the simple logout and accepting terms didn't work.
What finally helped was login to (https://id.vwgroup.io/account) , change country, logout, login, accept terms, change country back, logout, login as described here https://github.com/tillsteinbach/WeConnect-cli/issues/152.

Hope this helps others.
