### ISSUE TITLE
WeConnect fails due to not using Https with OAuth2

### ISSUE THREAD

**Issue by RaimondB** [tillsteinbach/WeConnect-mqtt#381]
I am getting this error in the logs 

`weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 194, in request
weconnect-mqtt-1  |     url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
weconnect-mqtt-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 238, in addToken
weconnect-mqtt-1  |     self.login()
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
weconnect-mqtt-1  |     response = self.doWebAuth(authorizationUrl)
weconnect-mqtt-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
weconnect-mqtt-1  |     afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
weconnect-mqtt-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
weconnect-mqtt-1  |     return self.request("GET", url, **kwargs)
weconnect-mqtt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
weconnect-mqtt-1  |     return super(WeConnectSession, self).request(
weconnect-mqtt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weconnect-mqtt-1  |   File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 188, in request
weconnect-mqtt-1  |     raise InsecureTransportError()
weconnect-mqtt-1  | oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.`

**Comment by luke-ff** [comment]
Same here (using docker):
`Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 343, in main
    mqttCLient.run()
  File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 782, in run
    self.updateWeConnect()
  File "/usr/local/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 462, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
  File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 194, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 205, in updateVehicles
    data = self.fetchData(url, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 373, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 194, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 238, in addToken
    self.login()
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
`

**Comment by tillsteinbach** [comment]
Are you on the latest version? This is a problem with accepting the terms and conditions.

**Comment by luke-ff** [comment]
Latest Version of what?  Volkswagen App?Should be recent version and up to date:Andreas LacknerFriedensflotte ***@***.*** 26.01.2025 um 11:15 schrieb Till Steinbach ***@***.***>:﻿
Are you on the latest version? This is a problem with accepting the terms and conditions.

**Comment by tillsteinbach** [comment]
no, latest version of WeConnect-mqtt

**Comment by luke-ff** [comment]
I’m using a QNAP-NAS with Container Station, I’ve installed Docker Image tillsteinbach/weconnect-mqtt:latest

Ach ja… sollten wir evtl. Deutsch schreiben?

++Luke

**Comment by RaimondB** [comment]
I found out in one of the other issues of this repo that you need to change your country to Germany and language to German in you Volkswagen id. Then you don't see the screen to accept the terms anymore after accepting once.

This does not impact the app or other websites.

Also you need to login to the vw id app once so that the app is authorised. I have a passat gte to uses the Volkswagen app. But I got access denied until I once logged into the vw id app. Even though it does give an error during login.

**Comment by tillsteinbach** [comment]
Huh, you still have the Volkswagen ID app? I worked with the now called „Volkswagen“ app with my Passat for more than a year. I think there is only one app for all cars.

**Comment by luke-ff** [comment]
I don't know why, but now WeConnect-mqtt works for me. Maybe it's the TC-Parameter (was Europe/Vienna, now set to Europe/Berlin) or the "-v"
