### ISSUE TITLE
data update stopped, no self-recovery (Broken pipe)

### ISSUE THREAD

**Issue by msome** [tillsteinbach/WeConnect-mqtt#44]
Hi, yesterday during charging of the car, the update of data read by WeConnect-mqtt stopped at 47% charge, even the car continued up to 93%. The container was still running, but did not provide newer data. 
I could only get it back running today when stopping & restarting (it did some version update) the docker container.

Maybe you have an idea what might have happened when taking a look to the trace below ?

I'm very sorry I cannot exactly tell which version was running when the failure happened, but it was not older than 1 or 2 months.
I don't know if there is a kind of logfile somewhere? If you can give me a hint where to find more persistent data about the failure, I can provide more. 

When connecting to the server, this error-trace was displayed:
```
weconnect-mqtt_1  | ERROR:paho.mqtt.client:failed to receive on socket: [Errno 32] Broken pipe
weconnect-mqtt_1  | ERROR:paho.mqtt.client:failed to receive on socket: [Errno 32] Broken pipe
weconnect-mqtt_1  | ERROR:paho.mqtt.client:failed to receive on socket: [Errno 32] Broken pipe
weconnect-mqtt_1  | ERROR:paho.mqtt.client:Caught exception in on_disconnect: timed out
weconnect-mqtt_1  | Exception in thread Thread-2:
weconnect-mqtt_1  | Traceback (most recent call last):
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
weconnect-mqtt_1  |     self.run()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
weconnect-mqtt_1  |     self._target(*self._args, **self._kwargs)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
weconnect-mqtt_1  |     self.loop_forever(retry_first_connection=True)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
weconnect-mqtt_1  |     rc = self.loop(timeout, max_packets)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1201, in loop
weconnect-mqtt_1  |     return self.loop_misc()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1628, in loop_misc
weconnect-mqtt_1  |     self._check_keepalive()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2430, in _check_keepalive
weconnect-mqtt_1  |     self._do_on_disconnect(rc)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
weconnect-mqtt_1  |     self.on_disconnect(self, self._userdata, rc)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 379, in on_disconnect_callback
weconnect-mqtt_1  |     self.reconnect()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
weconnect-mqtt_1  |     sock = self._create_socket_connection()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
weconnect-mqtt_1  |     return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
weconnect-mqtt_1  |     raise err
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
weconnect-mqtt_1  |     sock.connect(sa)
weconnect-mqtt_1  | socket.timeout: timed out

```

If the data provided is too inaccurate, please close the ticket. Thank you for your support.

**Comment by tillsteinbach** [comment]
It looks like this can happen when the MQTT broker is not reachable anymore. I hope it is fixed in 0.16.3 if not please reopen the ticket
