### ISSUE TITLE
Reconnecting not working

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#76]
This time I found a real issue ;-)

It seems that reconnecting to MQTT server is not working.
If I re-start my MQTT server (e.g. after change ACL- or passwd-file) I find these errors in the weconnect-mqtt logfile:

``2022-01-29T10:56:49+0000:ERROR:client:failed to receive on socket: [Errno 104] Connection reset by peer
2022-01-29T17:40:11+0000:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
2022-01-30T16:58:50+0000:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
2022-01-31T01:02:13+0000:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
2022-01-31T01:02:28+0000:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server due to timeout, will retry in 10 seconds
2022-01-31T01:02:43+0000:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server due to timeout, will retry in 10 seconds
2022-01-31T01:03:04+0000:ERROR:client:Caught exception in on_disconnect: [Errno 113] Host is unreachable
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 496, in on_disconnect_callback
    self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
``

The MQTT server was only down for some seconds (only restarting).

**Comment by tillsteinbach** [comment]
released in 0.29.0
