### ISSUE TITLE
Token expired kills the docker container

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#99]
Hi,

I just noticed that my WeConnect-mqtt container went down.
In the log file I found:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 165, in request
url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 204, in addToken
raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 171, in request
self.refresh()
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 55, in refresh
self.refreshTokens(
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 308, in refreshTokens
raise TemporaryAuthentificationError('Token could not be refreshed due to temporary WeConnect failure: {tokenResponse.status_code}')
weconnect.errors.TemporaryAuthentificationError: Token could not be refreshed due to temporary WeConnect failure: {tokenResponse.status_code}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 296, in main
mqttCLient.run()
File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 655, in run
self.updateWeConnect()
File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 404, in updateWeConnect
self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective)
File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 175, in update
self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 182, in updateVehicles
data = self.fetchData(url, force)
File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 344, in fetchData
statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 173, in request
self.login()
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 49, in login
response = self.doWebAuth(authorizationUrl)
File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 98, in doWebAuth
authorizationUrl = loginFormResponse.headers['Location']
File "/usr/local/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
return self._store[key.lower()][1]
KeyError: 'location'
```

**Comment by boredomwontgetus** [comment]
Same problem here since the update to the latest image.

**Comment by tillsteinbach** [comment]
Can confirm. This looks like it happens when the server does not respond correctly during login phase. I think there were some problems yesterday with WeConnect Servers. I'm about to push a fix but I'm not 100% sure that it will solve every corner case as right now the servers seem ok.

**Comment by tillsteinbach** [comment]
I hope this is fixed not in 0.30.2. Not entirely sure as I cannot test this without the server sending strange responses.

**Comment by tillsteinbach** [comment]
Will close this one for now. Please reopen if the error is appearing again.
